onlinestore/catalog/urls.py
from django.urls import path
from . import views
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', views.home, name='home'),
    path('contacts/', views.contacts, name='contacts'),
    path('<int:pk>/product/', views.product, name='product')
]

onlinestore/onlinestore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinestore/catalog/models.py
from django.db import models

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return f'{self.title} {self.description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')
    product_image = models.ImageField(upload_to='catalog/', verbose_name='изображение товара', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    purchase_price = models.IntegerField(verbose_name='цена за покупку')
    date_creation = models.DateTimeField(**NULLABLE, verbose_name='дата создания')
    last_modified_date = models.DateTimeField(**NULLABLE, verbose_name='дата последнего изменения')

    def __str__(self):
        return f'{self.title} {self.description}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('title',)

onlinestore/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product, Category


# Create your views here.
def home(request):
    catalog_list = Product.objects.all()
    category_list = Category.objects.all()
    context = {
        'object_list': catalog_list,
        'category_list': category_list,
        'title': 'Каталог'
    }
    return render(request, 'catalog/home.html', context)


def contacts(request):
    catalog_list = Product.objects.all()
    context = {
        'object_list': catalog_list,
        'title': 'Контакты'
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')

    return render(request, 'catalog/contacts.html', context)


def product(request, pk):
    product_item = Product.objects.get(pk=pk)
    catalog_list = Product.objects.filter(id=pk)
    context = {
        'object_list': catalog_list,
        'title': f'{product_item.title}'
    }
    return render(request, 'catalog/product.html', context)

onlinestore/catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore - {{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <ul class="list-unstyled">
        <li><a class="text-primary" href="{% url 'catalog:home' %}">Каталог</a></li>
        <li><a class="text-primary" href="{% url 'catalog:contacts' %}">Контакты</a></li>
    </ul>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>


                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">{{ object_list.1.category.title }}</a></li>
                    <li><a class="text-muted" href="#">{{ object_list.2.category.title }}</a></li>

                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

onlinestore/catalog/templates/catalog/base_product.html
<{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore - {{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <ul class="list-unstyled">
        <li><a class="text-primary" href="{% url 'catalog:home' %}">Каталог</a></li>
        <li><a class="text-primary" href="{% url 'catalog:contacts' %}">Контакты</a></li>
    </ul>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>

        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

onlinestore/catalog/templates/catalog/contacts.html
    {% extends 'catalog/base.html' %}

    {% block content %}
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <input type="submit" class="btn btn-lg btn-block btn-outline-primary" value="Отправить">
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

onlinestore/catalog/templates/catalog/home.html
    {% extends 'catalog/base.html' %}
    {% block content %}
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.purchase_price }} ₽</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.description|slice:":82" }}</li>
                    </ul>
                    <div class="btn-group">
                    <a href="{% url 'catalog:product' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

onlinestore/catalog/templates/catalog/includes/inc_catalog_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

onlinestore/catalog/templates/catalog/product.html
{% extends 'catalog/base_product.html' %}
{% block content %}
{% load static %}
{% load my_tags %}

<div class="col">
    {% for object in object_list %}
    <div class="card shadow-sm">
        <img class="card-img-top"
            src="{{ object.product_image|mymedia }}"
            alt="Card image cap">

        <div class="card-body">
            <p class="card-text"> - {{ object.purchase_price }} ₽</p>
            <p class="card-text"> - {{ object.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-primary">Добавить в корзину</button>

                </div>
                <small class="text-body-secondary">9 mins</small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}